version: '2.1'

services:
  node-expo-push-notification:
    image: node-expo-push-notification
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 1234:1234
      - 9229:9229
    ## set your startup file here
    command: node --inspect app.js